name: Bi Weekley Release
description: Count the number of days since the last automatic release and set it as an environment variable.
inputs:
  CHANNEL:
    required: true
    description: "The channel to get the version to (cloud, CCU)."
  LAST_AUTOMATED_RELEASE:
    required: false
    description: "The date of the last release."

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        last_automated_release_date=${{ inputs.LAST_AUTOMATED_RELEASE}}
        current_date=$(date +%s)
#        release_date=$(git log -1 --format=%ct $last_release)
        time_diff=$(( (current_date - last_automated_release_date) / (60*60*24) ))
        echo "Time difference is $time_diff days"
        if [ "$time_diff” -ge 14 ]; then
          echo "14 days have passed since the release.”
          # Perform additional actions here
        else
          echo "Less than 14 days have passed since the release.”
        fi
