version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "@elementor/*"
    reviewers:
      - "Nevoss"
    commit-message:
      prefix: "Internal: "
    groups:
      elementor-packages:
        patterns:
          - "@elementor/*"
