version: '3.1'

services:

  wordpress:
    image: wordpress
    ports:
      - 4000:80
    environment:
      WORDPRESS_DB_PASSWORD: example
      ABSPATH: /usr/src/wordpress/
    volumes:
      - ./local-site/site:/var/www/html
      - .:/var/www/html/wp-content/plugins/elementor

  cli:
    image: wordpress:cli
    volumes:
      - ./local-site/site:/var/www/html
      - .:/var/www/html/wp-content/plugins/elementor

  mysql:
    image: mysql:5.7
    volumes:
      - ./local-site/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress_test

  wordpress_phpunit:
    image: chriszarate/wordpress-phpunit
    environment:
      PHPUNIT_DB_HOST: mysql
    volumes:
      - .:/app
      - testsuite:/tmp

  wordpress_e2e_tests:
    image: wordpress
    ports:
    - 4001:80
    environment:
      WORDPRESS_DB_NAME: wordpress_e2e_tests
      WORDPRESS_DB_PASSWORD: example
      ABSPATH: /usr/src/wordpress/
    volumes:
    - wordpress_e2e_tests:/var/www/html
    - .:/var/www/html/wp-content/plugins/elementor

  cli_e2e_tests:
    image: wordpress:cli
    volumes:
    - wordpress_e2e_tests:/var/www/html
    - .:/var/www/html/wp-content/plugins/elementor

volumes:
  testsuite:
  wordpress_e2e_tests:
