name: Bump Channel Version
description: Bump the version of the current channel, and set it as an environment variable.

inputs:
  CHANNEL:
    required: true
    description: 'The channel to bump the version to (cloud, beta).'
  MAINTAIN_USERNAME:
    required: true
  MAINTAIN_EMAIL:
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
            git config user.name ${{ inputs.MAINTAIN_USERNAME }}
            git config user.email ${{ inputs.MAINTAIN_EMAIL }}
            
            CHANNEL_VERSION=$(node -p "require('./package.json').channels.${{ inputs.CHANNEL }}")
            node ./.github/scripts/update_channel_version.js ${{ inputs.CHANNEL }}
          
            CHANNEL_VERSION=$(node -p "require('./package.json').channels.${{ inputs.CHANNEL }}")
            git commit -am "Bump ${{ inputs.CHANNEL }} version to $CHANNEL_VERSION"
            git push