name: Bump Channel Version
description: Bump the version of the current channel, and set it as an environment variable.

inputs:
  CHANNEL:
    required: true
    description: 'The channel to bump the version to (cloud, beta).'
  GITHUB_ACTOR:
    required: true
    description: 'The github actor.'
  CLEAN_PACKAGE_VERSION:
    required: true
    description: 'The current package version.'
  MAINTAIN_USERNAME:
    required: true
    description: 'The username of the maintainer.'
  MAINTAIN_EMAIL:
    required: true
    description: 'The email of the maintainer.'

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
            git config user.name ${{ inputs.MAINTAIN_USERNAME }}
            git config user.email ${{ inputs.MAINTAIN_EMAIL }}
            
            echo "pwd: $(pwd)"
            echo "ls: $(ls)"
            CURRENT_CHANNEL_VERSION=git ls-remote --tags ${{ inputs.GITHUB_ACTOR }} | grep ${{ inputs.CHANNEL }} | grep v${{ inputs.CLEAN_PACKAGE_VERSION }} | awk '{print $2}' | cut -d/ -f3 | sort -V | tail -1 | awk -F'${{ inputs.CHANNEL }}' '{print $2}'
            if [ -z "$CURRENT_CHANNEL_VERSION" ]; then
              CURRENT_CHANNEL_VERSION=0
            fi
            NEW_CHANNEL_VERSION=$((CURRENT_CHANNEL_VERSION+1))
            
            echo "NEW_CHANNEL_VERSION=${NEW_CHANNEL_VERSION}" >> $GITHUB_ENV