name: Build Plugin
description: Inject the given version into the plugin files and then build it and zip it.

inputs:
  PACKAGE_VERSION:
    required: true
    description: 'The version to inject into the plugin package.json file.'
  BUILD_SCRIPT_PATH:
    required: true
    description: 'The full path of the script to build the plugin.'
  UPDATE_VERSION_SCRIPT_PATH:
    required: true
    description: 'The path to the script that updates the version in the plugin PHP files.'

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
            if [ "${{ inputs.PACKAGE_VERSION }}" == "" ] || [ "${{ inputs.PACKAGE_VERSION }}" == "undefined" ];
              then
                echo "PACKAGE_VERSION is empty string or undefined"
                exit 1
            fi

            bash ${{ inputs.UPDATE_VERSION_SCRIPT_PATH }}
            bash ${{ inputs.BUILD_SCRIPT_PATH }}
            
      env:
        PACKAGE_VERSION: ${{ inputs.PACKAGE_VERSION }}
