name: Remove Git Tag
description: Remove a Git tag from the remote repository.

inputs:
  MAINTAIN_USERNAME:
    description: 'The username of the user that will create the tag.'
    required: true
  MAINTAIN_EMAIL:
    description: 'The email of the user that will create the tag.'
    required: true
  TAG_NAME:
    description: 'The message of the tag.'
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        git config user.name ${{ inputs.MAINTAIN_USERNAME }}
        git config user.email ${{ inputs.MAINTAIN_EMAIL }}
        git push origin :refs/tags/${{ inputs.TAG }}
        echo "Remove tag v${{ inputs.TAG }}"
