name: Remove Git Tag
description: Remove a Git Tag from the remote repository.

inputs:
  PACKAGE_VERSION:
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash 
      run: |
            git tag -d v${PACKAGE_VERSION}
            git push origin :refs/tags/v${PACKAGE_VERSION}
      
