name: Remove Git Tag
description: Remove a Git tag from the remote repository.

inputs:
  TAG_NAME:
    description: 'The tag name to remove (e.g. v3.11.2-cloud-rc)'
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        # Ignore errors if the tag doesn't exist, log and continue.
        if git push --delete --quiet origin "${{ inputs.TAG_NAME }}" 2>/dev/null; then
          echo "Tag successfully deleted."
        else
          echo "Tag doesn't exist, but continuing script execution."
        fi
