name: Remove Git Tag
description: Remove a Git Tag from the remote repository.

inputs:
  PACKAGE_VERSION:
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash 
      run: |
            git push --delete origin ${PACKAGE_VERSION} || echo "Tag ${PACKAGE_VERSION} not found on remote"