name: Remove Git Tag
description: Remove a Git tag from the remote repository.

inputs:
  TAG_NAME:
    description: 'The message of the tag.'
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        git push origin :refs/tags/${{ inputs.TAG_NAME }}
