name: "🐞 Bug report"
description: "Report a bug if something isn't working as expected in the Elementor"
title: "🐞 Bug report: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        ## BEFORE POSTING YOUR ISSUE

        - Please create GitHub issues only for bugs and feature requests. GitHub issues ARE NOT FOR SUPPORT!

        - If you have questions or need general support,  Please use:  https://wordpress.org/support/plugin/elementor

        - For help and support from the Elementor community, see: https://www.facebook.com/groups/Elementors/

        - To read more about Elementor, check out our documentation: https://docs.elementor.com

        - Developers docs are located at https://developers.elementor.com/

        ==== Guidelines ====

        - Search this repository (top of the page) for the issue, and make sure it has not been fixed or reported before.
        - Make sure you are using the most updated versions of Elementor, WordPress & your theme.
        - Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
        - Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).
        - If you're requesting a new feature, explain why you'd like it to be added. Try to add as much detail as you can, and be specific.
