name: "❓ Support Question"
description: "If you have a support question, please refer to our docs or our Facebook Elementor community.
If this doesn't look right, choose a different type."
body:
  - type: checkboxes
    id: support_question
    attributes:
      label: "❓ Support Question"
      options:
        - label: "Please create GitHub issues only for bugs and feature requests. GitHub issues ARE NOT FOR SUPPORT!"
        - label: "If you have questions or need general support, please use:  https://wordpress.org/support/plugin/elementor"
        - label: "For help and support from the Elementor community, see: https://www.facebook.com/groups/Elementors/"
        - label: "To read more about Elementor, check out our documentation: https://docs.elementor.com"
        - label: "Developers docs are located at: https://developers.elementor.com/"
