name: Generate Temp Changelog
description: Generate a changelog between two versions.

on:
  workflow_dispatch:
    inputs:
      toTag:
        description: 'To Tag'
        required: true
        type: string
        default: 'main'

      fromTag:
        description: 'From Tag'
        required: true
        type: string
        default: 'main'

      saveChangelog:
        description: 'Save Changelog?'
        required: true
        type: boolean

jobs:
  generate-changelog:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update Changelog
        id: update_changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          toTag: ${{ github.event.inputs.toTag }}
          fromTag: ${{ github.event.inputs.fromTag }}
          writeToFile: ${{ github.event.inputs.saveChangelog }}
          includeInvalidCommits: "true"
          includeRefIssues: "false"
          useGitmojis: "false"
          excludeTypes: ""

      - name: Format Changelog
        id: format_changelog
        run: |
          changes=$(sed 's/^-/*/g; s#(\(https://github.com/mark-elementor/changelog-test/commit/\)\([^)]*\)) - #[\2](\1\2)  \n#g; s/\[\]//g' <<< "${{ steps.update_changelog.outputs.changes }}")
          echo "$changes" > CHANGELOG.md

      - name: Upload Changelog as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Changelog
          path: CHANGELOG.md

      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v4
        if: github.event.inputs.saveChangelog == 'true'
        with:
          branch: main
          commit_message: 'docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
          file_pattern: CHANGELOG.md
