name: Create Git Tag
description: Generate a new Git version and push it to the remote repository.

inputs:
  MAINTAIN_USERNAME:
    required: true
  MAINTAIN_EMAIL:
    required: true
  MESSAGE:
    required: false

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        git config user.name ${{ inputs.MAINTAIN_USERNAME }}
        git config user.email ${{ inputs.MAINTAIN_EMAIL }}
        echo "Create tag v${{ inputs.MESSAGE }}"
        git tag "v${{ inputs.MESSAGE }}"
        git push origin "v${{ inputs.MESSAGE }}"
