name: Get New Release Name
description: Get the new release name from ${{ inputs.PLUGIN_NAME }}.php (sets by 'Create Rc Tag' action) and set it as an environment variable.

inputs:
  BUILD_ZIP_FILE_PATH:
    description: 'The path to the zip file.'
    required: true
  PLUGIN_NAME:
    description: 'The name of the plugin.'
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
          unzip ${{ inputs.BUILD_ZIP_FILE_PATH }} ${{ inputs.PLUGIN_NAME }}/${{ inputs.PLUGIN_NAME }}.php
          RELEASE_NAME=$(grep "Version:" ${{ inputs.PLUGIN_NAME }}.php | awk '{print $3}')
          if [ -z "$RELEASE_NAME" ]; then
            echo "RELEASE_NAME is empty"
            exit 1
          fi

          echo "RELEASE_NAME=${RELEASE_NAME}" >> $GITHUB_ENV