name: Get New Release Name
description: Get the new release name from elementor.php (sets by 'Create Rc Tag' action) and set it as an environment variable.

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
          RELEASE_NAME=$(grep "Version:" elementor.php | awk '{print $3}')

          if [ -z "$RELEASE_NAME" ]; then
            echo "RELEASE_NAME is empty"
            exit 1
          fi

          echo "RELEASE_NAME=${RELEASE_NAME}" >> $GITHUB_ENV