name: Get New Release Name
description: Get the new release name from elementor.php (sets by 'Create Rc Tag' action) and set it as an environment variable.

inputs:
  BUILD_ZIP_FILE_PATH:
    description: 'The path to the zip file.'
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
          RELEASE_NAME=$( unzip -p ${{ inputs.BUILD_ZIP_FILE_PATH }} elementor.php | grep 'Version:' | awk '{print $3}' )
          if [ -z "$RELEASE_NAME" ]; then
            echo "RELEASE_NAME is empty"
            exit 1
          fi

          echo "RELEASE_NAME=${RELEASE_NAME}" >> $GITHUB_ENV