name: Get New Release Name
description: Get the new release name, and set it as an environment variable.

inputs:
  REPO_NAME:
    required: true
    description: 'The repo name to get the new release name for.'
  CLEAN_PACKAGE_NAME:
    required: true
    description: 'The clean package version to get the new release name for.'

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
          CHANNEL_VERSION=$(node -p "require('./package.json').channels.${{ github.event.inputs.chennel }}")
          echo "CHANNEL_VERSION=${CHANNEL_VERSION}" >> $GITHUB_ENV

          VERSION_CHANNEL=$(echo ${{ inputs.CLEAN_PACKAGE_NAME }} | sed 's/-[^-]*$//')

          RELEASE_NAME=${{ inputs.REPO_NAME }}-${VERSION_CHANNEL}${CHANNEL_VERSION}
          echo "RELEASE_NAME=${RELEASE_NAME}" >> $GITHUB_ENV