name: Get Changelog From changelog and readme Text Files
description: Get Changelog From changelog and readme Text Files - publish in wordpress.org.

inputs:
  VERSION:
    description: 'Package Version'
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        VERSION: ${{ inputs.VERSION }}
      run: |
        npm install --no-package-lock --no-save marked@2.0.6
        node ./.github/scripts/get-changelog-from-change-txt.js
