name: Build Packages
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith( github.repository, 'elementor/' )
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install Dependencies
        run: cd ./packages/editor && npm ci
      - name: Build History
        run: cd ./packages/editor/packages/history && npm run build
