name: Create Release Branch
# Create a release branch from the current release branch ref 

on:
  workflow_dispatch:

jobs:
  create-branch:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Create Branch
        run: |
          git config --global user.email "ElementorBot@elementor.com"
          git config --global user.name "ElementorBot"

          #e.g refs/heads/3.14
          current_branch_version=$(echo ${{ github.ref }} | cut -d'/' -f 3)
          echo "Current branch version is $current_branch_version"

          # e.g 3.14
          if ! [[ $current_branch_version =~ ^[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid version ${{ github.ref }}"
            exit 1
          fi

          # e.g 3.15
          increment_version=$(echo $current_branch_version | awk -F. -v OFS=. '{$NF++;print}')
          echo "Increment version is $increment_version"

          git checkout -b $increment_version
          npm version "$increment_version.0" --no-git-tag-version
          git add package.json
          git add package-lock.json

          git commit -m "Release branch $increment_version created"
          git push origin $increment_version
