name: Create Tag
# Required secrets for this workflow: MAINTAIN_USERNAME, MAINTAIN_EMAIL, SLACK_TOKEN, MAINTAIN_TOKEN, and a var: SLACK_TAG_CHANNELS.

on:
  workflow_dispatch:
    inputs:
      type:
        type: choice
        description: 'Tag Type'
        required: true
        default: 'rc'
        options:
          - 'rc'
          - 'hotfix'
jobs:
  create-tag:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MAINTAIN_TOKEN }}
      - name: Get Configuration
        id: configuration
        uses: maork-elementor/json-to-variables@main
        with:
            filename: './.github/workflows/config.json'
            prefix: config
      - name: Test permissions
        uses: ./.github/workflows/permissions
        with:
          ENVIRONMENT: ${{ env.config_deployment_environment }}
          DEPLOYMENT_PERMITTED: ${{ env.config_deployment_permitted }}
          DEPLOYMENT_REPOSITORY_OWNER: ${{ env.config_deployment_repository_owner }}
      - name: Install Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: Bump tag version
        uses: ./.github/workflows/bump-version
        with:
          CHANNEL: ${{ github.event.inputs.type }}
      - name: Install Dependencies
        run: |
          echo "PACKAGE_VERSION=${PACKAGE_VERSION}" >> $GITHUB_ENV
          npm ci
      - name: Build plugin
        uses: ./.github/workflows/build-plugin
        with:
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}
          BUILD_SCRIPT_PATH: "./.github/scripts/build-zip.sh"
      - name: Upload zip file to GitHub actions artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PLUGIN_ZIP_FILENAME }}
          path: ${{ env.PLUGIN_ZIP_PATH }}
          if-no-files-found: error
      - name: Create Git tag
        uses : ./.github/workflows/create-git-tag
        with:
          MAINTAIN_USERNAME: ${{ secrets.MAINTAIN_USERNAME }}
          MAINTAIN_EMAIL: ${{ secrets.MAINTAIN_EMAIL }}
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}
      - name: Push version
        uses : ./.github/workflows/push-new-version
        with:
          MAINTAIN_USERNAME: ${{ secrets.MAINTAIN_USERNAME }}
          MAINTAIN_EMAIL: ${{ secrets.MAINTAIN_EMAIL }}
          COMMIT_MESSAGE: "Bump ${{ env.PACKAGE_VERSION }}"
      - name: Get artifact URL
        run: |
          ACTION_RUN="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          echo "ACTION_RUN=${ACTION_RUN}" >> $GITHUB_ENV
      - name: Send slack message
        uses: ./.github/workflows/slack-notify
        with:
          MESSAGE: "@here Elementor `${{ env.PACKAGE_VERSION }}` Tag created, please review changes. The build can be found in the artifacts : ${{ env.ACTION_RUN }}"
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_CHANNELS: ${{ vars.SLACK_TAG_CHANNELS }}
        
