name: Elementor Tests / Init

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-16.04
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@master
      - name: Block non-permitted users
        uses: StyleShit/action-whitelist-users@master
        with:
          whitelist-file: '.github/workflows/whitelist.txt'
      - name: Elementor Tests / Init
        env:
          TOKEN: ${{ secrets.DEVOPS_TOKEN }}
          REMOTE_TESTS_REPO: ${{ secrets.REMOTE_TESTS_REPO }}
          HEAD_REPO: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
        run: |
          curl -X POST https://api.github.com/repos/${{ env.REMOTE_TESTS_REPO }}/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ env.TOKEN }} \
          --data '{"event_type": "remote-tests", "client_payload": { "repository": "${{ env.HEAD_REPO }}", "sha": "${{ github.head_ref || github.sha }}", "run_id": "${{ github.run_id }}" }}'
