name: Fetch Merged PRs After Tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag after which to fetch merged PRs'
        required: true

jobs:
  fetch-merged-prs:
    runs-on: ubuntu-latest

    steps:
    - name: Get Tag Date
      id: get-tag-date
      run: |
        TAG_DATE=$(curl -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/elementor/elementor/git/refs/tags/${{ github.event.inputs.tag }}" | jq -r '.object.url' | xargs curl -H "Accept: application/vnd.github.v3+json" | jq -r '.committer.date')
        echo "TAG_DATE=$TAG_DATE" >> $GITHUB_ENV

    - name: Fetch merged PRs after tag
      run: |
        # Use GitHub's API to fetch PRs
        pr_data=$(curl -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/elementor/elementor/pulls?state=closed&base=3.16&per_page=100")

        # Extract PRs merged after the specific tag's date and print in desired format
        echo "$pr_data" | jq -r --arg TAG_DATE "$TAG_DATE" '.[] | select(.merged_at > $TAG_DATE) | "#\(.number) - \(.title)"'
