name: Fetch Merged PRs After Release

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release after which to fetch merged PRs'
        required: true
      branch:
        description: 'Branch to fetch merged PRs from'
        required: true
        default: 'main'

jobs:
  fetch-merged-prs:
    runs-on: ubuntu-latest

    steps:
    - name: Get Release Date
      id: get-release-date
      run: |
        RELEASE_DATE=$(curl -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/elementor/elementor/releases/tags/${{ github.event.inputs.release }}" | jq -r '.published_at')
        echo "RELEASE_DATE=$RELEASE_DATE" >> $GITHUB_ENV

    - name: Fetch merged PRs after release
      run: |
        pr_data=$(curl -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/elementor/elementor/pulls?state=closed&base=${{ github.event.inputs.branch }}&per_page=100")
        echo "$pr_data" | jq -r --arg RELEASE_DATE "$RELEASE_DATE" '.[] | select(.merged_at > $RELEASE_DATE) | "#\(.number) - \(.title)"'
