name: Generate Temp Changelog

on:
  workflow_dispatch:
    inputs:
      toTag:
        description: 'To Tag'
        required: true
        type: string
        default: 'main'

      fromTag:
        description: 'From Tag'
        required: true
        type: string
        default: 'main'

      saveChangelog:
        description: 'Save Changelog?'
        required: true
        type: boolean

jobs:
  generate-changelog:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # - name: Update Changelog
      #   id: update_changelog
      #   uses: requarks/changelog-action@v1
      #   with:
      #     token: ${{ github.token }}
      #     toTag: ${{ github.event.inputs.toTag }}
      #     fromTag: ${{ github.event.inputs.fromTag }}
      #     writeToFile: ${{ github.event.inputs.saveChangelog }}
      #     includeInvalidCommits: "true"
      #     includeRefIssues: "false"
      #     useGitmojis: "false"
      #     excludeTypes: ""

      - name: Update Changelog
        id: update_changelog
        uses: mikepenz/release-changelog-builder-action@v4.0.0
        with:
          ignorePreReleases: "false"
          fromTag: ${{ github.event.inputs.toTag }}
          toTag: ${{ github.event.inputs.fromTag }}
          token: ${{ github.token }}
          fetchViaCommits: "true"

      - name: Format Changelog
        id: format_changelog
        run: |
          echo "${{ steps.update_changelog.outputs.changes }}" > CHANGELOG.md

      - name: Upload Changelog as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Changelog
          path: CHANGELOG.md

      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v4
        if: github.event.inputs.saveChangelog == 'true'
        with:
          branch: main
          commit_message: 'docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
          file_pattern: CHANGELOG.md
