name: Image Compare 2

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-16.04
    strategy:
      fail-fast: false
      matrix:
        wordpress_versions: ['latest', '5.4', '5.3', '5.2', '5.1', '5.0']
    name: WordPress ${{ matrix.wordpress_versions }}
    steps:
      - name: Startup MySQL service
        run: sudo /etc/init.d/mysql start
      - name: Checkout source code
        uses: actions/checkout@master
      - name: Install Dependencies
        run: |
          bash bin/cli-install-wp-tests.sh wordpress_test root root localhost ${{ matrix.wordpress_versions }} image-compare
      - name: PHP7.3
        run: php7.3
