name: Image Compare 2

on: [ push, pull_request ]

jobs:
  run:
    runs-on: ubuntu-16.04
    strategy:
      fail-fast: false
      matrix:
        wordpress_versions: [ 'latest' ]
    name: WordPress ${{ matrix.wordpress_versions }}
    steps:
      - name: Startup MySQL service
        run: sudo /etc/init.d/mysql start
      - name: Checkout source code
        uses: actions/checkout@master
      - name: Install Screenshotter
        run: |
          npm install -g @efelementor/screenshotter --registry=https://npm.pkg.github.com/efelementor
      - name: Install Dependencies
        run: |
          elementor-vrt-install --wp_version=${{ matrix.wordpress_versions }}
      - name: Import Tamplate(s)
        run: |
          elementor-vrt-import-templates
      - name: Build Package & Run Tests
        run: |
          elementor-vrt-run-test
