name: One Click GA Release

on:
  workflow_dispatch:
    inputs:
      pre_release:
        type: boolean
        description: "Pre-release?"
        default: true
        required: false
      channel:
        required: true
        type: choice
        description: Select a channel
        options:
          - ga
          - beta

env:
  CHANNEL: ${{inputs.channel}}
  CHANGELOG_FILE: "temp-changelog.txt"

permissions:
  contents: write
  id-token: "write"

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout branch
        uses: actions/checkout@v3
        with:
          ref: ${{inputs.branch}}
      - name: Get Configuration
        id: configuration
        uses: rgarcia-phi/json-to-variables@9835d537368468c4e4de5254dc3efeadda183793
        with:
          filename: "./.github/workflows/config.json"
          prefix: config
      - name: Test permissions
        uses: ./.github/workflows/permissions
        with:
          ENVIRONMENT: ${{ env.config_deployment_environment }}
          DEPLOYMENT_PERMITTED: ${{ env.config_deployment_permitted }}
          DEPLOYMENT_REPOSITORY_OWNER: ${{ env.config_deployment_repository_owner }}
      - name: Install Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Set POSTFIX value
        id: set_postfix_value
        uses: ./.github/workflows/set-postfix-value
        with:
          PRERELEASE: ${{ github.event.inputs.pre_release }}
      - name: Env Vars Configure
        id: env_vars_configure
        uses: ./.github/workflows/env-vars-configure
        with:
          CHANNEL: ${{ env.CHANNEL }}
          REF: ${{ github.ref }}
          POSTFIX: ${{ steps.set_postfix_value.outputs.postfix }}
      - name: Bump Channel Version
        id: bump_channel_version
        uses: ./.github/workflows/bump-channel-version
        with:
          CLEAN_PACKAGE_VERSION: ${{ env.CLEAN_PACKAGE_VERSION }}
          CHANNEL: ${{ env.CHANNEL }}
          POSTFIX: ${{ steps.set_postfix_value.outputs.postfix }}
          OVERRIDE_PACKAGE_VERSION: true
      - name: Install Dependencies
        run: npm ci
      - name: Build plugin
        uses: ./.github/workflows/build-plugin
        with:
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}
          BUILD_SCRIPT_PATH: "./.github/scripts/build-zip.sh"
      - uses: actions/upload-artifact@v3
        with:
          name: ${{env.PLUGIN_ZIP_FILENAME}}
          path: ./${{env.PLUGIN_ZIP_FILENAME}}
