name: PHPUnit

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-16.04
    strategy:
      fail-fast: false
      matrix:
        wordpress_versions: ['latest', '5.5', '5.4', '5.3']
        php_versions: [ '5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0' ]
    name: WordPress ${{ matrix.wordpress_versions }} - PHP version ${{ matrix.php_versions }}
    env:
      WP_TESTS_DIR: /tmp/wordpress-tests-lib
    steps:
      - name: Startup MySQL service
        run: sudo /etc/init.d/mysql start
      - name: Checkout source code
        uses: actions/checkout@master
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_versions }}
      - name: Install Dependencies
        run: |
          bash bin/install-wp-tests.sh wordpress_test root root localhost ${{ matrix.wordpress_versions }}
          composer install
      - name: PHP5.6
        run: composer run test
