name: PR Linter
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
  merge_group:

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  pr_name_lint:
    runs-on: self-hosted
    if: startsWith( github.repository, 'elementor/' )
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install Dependencies
        if: ${{ github.event.pull_request.title != null }}
        run: npm install --no-package-lock --no-save @commitlint/config-conventional@12.1.1 @commitlint/cli@12.1.1
      - name: Run PR name linter
        if: ${{ github.event.pull_request.title != null }}
        # passing github.event.pull_request.title as an argument
        # to prevent a shell injection attack. Further reading:
        # https://securitylab.github.com/research/github-actions-untrusted-input/#exploitability-and-impact
        # https://securitylab.github.com/research/github-actions-untrusted-input/#remediation
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: echo "$TITLE" | npx commitlint
