name: Publish Cloud Version

on:
  workflow_dispatch:

jobs:
  poc-job:
    runs-on: ubuntu-20.04
    steps:
      - uses: ${GITHUB_WORKSPACE}/.github/workflows/slack-notify
        with:
          PACKAGE_VERSION: ${{ 'test version 123' }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_CHANNELS: ${{ "C03PMU9HK24" }}
