name: Publish Cloud Changelog

on:
  workflow_dispatch:
    inputs:
      CHANGELOG_CONTENT:
        description: 'The content of the changelog'
        required: true
      PACKAGE_VERSION:
        description: 'The version of the package'
        required: true

jobs:
  publish-changelog:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Install Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install Dependencies
        shell: bash
        run: |
            npm install --no-package-lock --no-save octokit@v2.0.19
            npm install --no-package-lock --no-save cheerio@v1.0.0-rc.12
      - name: Publish Changelog
        shell: bash
        run: |
          echo $(pwd)
          echo $(ls -la)
          cd ${GITHUB_WORKSPACE}/.github/scripts
          echo $(ls -la)
          node ${GITHUB_WORKSPACE}/.github/scripts/publish-cloud-changelog.js
        env:
          CHANGELOG_CONTENT: ${{ inputs.CHANGELOG_CONTENT }}
          GITHUB_TOKEN: ${{ secrets.MAINTAIN_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: "elementor-cloud-changelog"
          TEMPLATE_URL: "https://elementor.com/pro/changelog/"
          PACKAGE_VERSION: ${{ inputs.PACKAGE_VERSION }}