name: Publish V2
# Required secrets for this workflow: MAINTAIN_USERNAME, MAINTAIN_EMAIL, SLACK_TOKEN, SLACK_CHANNELS, MAINTAIN_TOKEN

on:
  workflow_dispatch:
    inputs:
      chennel:
        type: choice
        description: 'The channel to publish to'
        required: true
        default: 'cloud'
        options:
          - 'ga'
          - 'cloud'
          - 'beta'
      pre_release:
        type: boolean
        description: 'Is this a pre-release?'
        required: false

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Validate Channel To Current Tag
        run: |
          echo "CHANNEL=${{ github.event.inputs.chennel }}" >> $GITHUB_ENV
          echo "CURRENT_TAG=${{ github.ref }}" >> $GITHUB_ENV
          if [[ $CURRENT_TAG != *$CHANNEL* ]]; then
            echo "The current tag is not for the channel you want to publish to."
            exit 1
          fi
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MAINTAIN_TOKEN }}
      - name: Install Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: Get Current Package Version
        uses: ./.github/workflows/get-current-package-version
      - name: Get Clean Package Name
        run: |
          CLEAN_PACKAGE_NAME=${{ github.ref }}
          CLEAN_PACKAGE_NAME=${CLEAN_PACKAGE_NAME##*/}
          CLEAN_PACKAGE_NAME=${CLEAN_PACKAGE_NAME:1}
          echo "CLEAN_PACKAGE_NAME=${CLEAN_PACKAGE_NAME}" >> $GITHUB_ENV
      - name: Download release assets
        uses: robinraju/release-downloader@v1.7
        with:
          tag: v${{ env.CLEAN_PACKAGE_NAME }}
          fileName: ${{ github.event.repository.name }}-${{ env.CLEAN_PACKAGE_NAME }}.zip
          out-file-path: /tmp/
      - name: Upload zip file to GitHub actions artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-${{ env.CLEAN_PACKAGE_NAME }}.zip
          path: /tmp/${{ env.CLEAN_PACKAGE_NAME }}.zip
          if-no-files-found: error
      - name: Get channel version
        run: |
          CHANNEL_VERSION=$(node -p "require('./package.json').channels.${{ github.event.inputs.chennel }}")
          echo "CHANNEL_VERSION=${CHANNEL_VERSION}" >> $GITHUB_ENV
      - name: Create Git tag
        uses : ./.github/workflows/create-git-tag
        with:
          MAINTAIN_USERNAME: ${{ secrets.MAINTAIN_USERNAME }}
          MAINTAIN_EMAIL: ${{ secrets.MAINTAIN_EMAIL }}
          PACKAGE_VERSION: ${{ github.event.repository.name }}-${{ env.CLEAN_PACKAGE_NAME }}-${{ env.CHANNEL_VERSION }}
      - name: Generate changelog
        uses : ./.github/workflows/generate-changelog
        with:
          TOKEN: ${{ secrets.MAINTAIN_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          HEAD_BRANCH_NAME: ${{ github.ref }}
          BASE_TAG_NAME: main
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.PACKAGE_VERSION }}
          files: elementor-*.zip
          prerelease: ${{ github.event.inputs.pre_release }}
          body_path: temp-changelog.txt
        env:
          GITHUB_TOKEN: ${{ secrets.MAINTAIN_TOKEN }}
      - name: Send slack message
        uses: ./.github/workflows/slack-notify
        with:
          MESSAGE: "@here Elementor ${{ env.PACKAGE_VERSION }} has been released! Saddle up partners! :tada:"
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_CHANNELS: ${{ secrets.SLACK_CHANNELS }}
