name: Publish V2
# Required secrets for this workflow: MAINTAIN_USERNAME, MAINTAIN_EMAIL, SLACK_TOKEN, SLACK_CHANNELS, MAINTAIN_TOKEN

on:
  workflow_dispatch:
    inputs:
      pre_release:
        type: boolean
        description: 'Is this a pre-release?'
        required: false

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MAINTAIN_TOKEN }}
      - name: Install Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: Parse ref branch name
        uses: ./.github/workflows/parse-branch-name
        with:
          BRANCH_NAME: ${{ github.ref }}
      - name: Download release zip file from RC tag artifact
        uses: robinraju/release-downloader@v1.7
        with:
          tag: v${{ env.CLEAN_PACKAGE_NAME }}
          fileName: ${{ github.event.repository.name }}-${{ env.CLEAN_PACKAGE_NAME }}.zip
          out-file-path: /tmp/
      - name: Upload zip file to GitHub actions artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-${{ env.CLEAN_PACKAGE_NAME }}.zip
          path: /tmp/${{ github.event.repository.name }}-${{ env.CLEAN_PACKAGE_NAME }}.zip
          if-no-files-found: error
      - name: Get Release Name
        uses : ./.github/workflows/get-release-name
        with:
          BUILD_ZIP_FILE_PATH: /tmp/${{ github.event.repository.name }}-${{ env.CLEAN_PACKAGE_NAME }}.zip
          PLUGIN_NAME: ${{ github.event.repository.name }}
      - name: Rename Release zip file to new release name
        uses : ./.github/workflows/copy-file
        with:
          SOURCE_PATH: /tmp/${{ github.event.repository.name }}-${{ env.CLEAN_PACKAGE_NAME }}.zip
          DESTINATION_PATH: /tmp/${{ env.RELEASE_FILENAME }}.zip
      - name: Create Git tag
        uses : ./.github/workflows/create-git-tag
        with:
          MAINTAIN_USERNAME: ${{ secrets.MAINTAIN_USERNAME }}
          MAINTAIN_EMAIL: ${{ secrets.MAINTAIN_EMAIL }}
          MESSAGE: ${{ env.RELEASE_NAME }}
      - name: Download release chengelog from RC tag artifact
        uses: robinraju/release-downloader@v1.7
        with:
          tag: v${{ env.CLEAN_PACKAGE_NAME }}
          fileName: changelog.txt
          out-file-path: /tmp/
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_NAME }}
          files: /tmp/${{ env.RELEASE_FILENAME }}.zip
          prerelease: ${{ github.event.inputs.pre_release }}
          body_path: /tmp/changelog.txt
        env:
          GITHUB_TOKEN: ${{ secrets.MAINTAIN_TOKEN }}
      - name: Send slack message
        uses: ./.github/workflows/slack-notify
        with:
          MESSAGE: "@here Elementor ${{ env.RELEASE_NAME }} has been released! Saddle up partners! :tada:"
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_CHANNELS: ${{ secrets.SLACK_CHANNELS }}
