name: Publiush Cloud Changelog

on: [workflow_dispatch]

inputs:
  CHANGELOG_CONTENT:
    description: 'The content of the changelog'
    required: true
  PACKAGE_VERSION:
    description: 'The version of the package'
    required: true

jobs:
  publish-changelog:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Dependencies
        shell: bash
        run: |
          npm install cheerio@v1.0.0-rc.12
          npm install octokit@v2.0.19
      - name: Publish Changelog
        shell: bash
        run: |
          node ./.github/scripts/publish-cloud-changelog.js
        env:
          CHANGELOG_CONTENT: ${{ inputs.CHANGELOG_CONTENT }}
          GITHUB_TOKEN: ${{ secrets.MAINTAIN_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: "elementor-cloud-changelog"
          TEMPLATE_URL: "https://elementor.com/pro/changelog/"
          PACKAGE_VERSION: ${{ inputs.PACKAGE_VERSION }}