name: Publish Cloud Version

on:
  workflow_dispatch:

jobs:
  poc-job:
    runs-on: ubuntu-20.04
    steps:
      - uses: ./.github/workflows/slack-notify
        with:
          PACKAGE_VERSION: ${{ "test-PACKAGE_VERSION" }}
          SLACK_TOKEN: ${{ "test-SLACK_TOKEN" }}
          SLACK_CHANNELS: ${{ "test-SLACK_CHANNELS" }}
