name: Publish Path Version

on:
  workflow_dispatch:

jobs:
  bump-version:
    if: (github.actor == 'ronkelementor' || github.actor == 'KingYes') && startsWith(github.repository, 'elementor/')
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MAINTAIN_TOKEN }}
          ref: develop
      - name: Bump version
        run: |
          npm config set git-tag-version false
          npm version patch
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          echo "PACKAGE_VERSION=${PACKAGE_VERSION}" >> $GITHUB_ENV
      - name: Push new version to develop
        env:
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}
          MAINTAIN_EMAIL: ${{ secrets.MAINTAIN_EMAIL }}
          MAINTAIN_USERNAME: ${{ secrets.MAINTAIN_USERNAME }}
        run: |
          bash "${GITHUB_WORKSPACE}/.github/scripts/update-readme-stable-version.sh"
          bash "${GITHUB_WORKSPACE}/.github/scripts/update-version-elementor-php.sh"
          bash "${GITHUB_WORKSPACE}/.github/scripts/commit-push-bump.sh"
  publish:
    needs: bump-version
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MAINTAIN_TOKEN }}
          ref: master
      - name: Merge develop -> master
        uses: devmasx/merge-branch@a1752b9ba42bb417ec19be7dc974e2faf77d3ef2 # v1.3.1
        with:
          type: now
          from_branch: develop
          target_branch: master
          github_token: ${{ secrets.MAINTAIN_TOKEN }}
      - name: Checkout updated master branch
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MAINTAIN_TOKEN }}
          ref: master
      - name: Install Dependencies
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          echo "PACKAGE_VERSION=${PACKAGE_VERSION}" >> $GITHUB_ENV
          npm ci
      - name: Build
        env:
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}
        run: |
          bash "${GITHUB_WORKSPACE}/.github/scripts/build-zip.sh"
      - name: Publish to WordPress.org SVN
        env:
          PLUGIN_VERSION: ${{ env.PACKAGE_VERSION }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        run: |
          bash "${GITHUB_WORKSPACE}/.github/scripts/publish-to-wordpress-org.sh"
      - name: Upload zip file to GitHub actions artifact
        uses: actions/upload-artifact@v2
        with:
          name: elementor-${{ env.PACKAGE_VERSION }}
          path: ${{ github.workspace }}/elementor/**/*
      - name: Create tag
        env:
          MAINTAIN_EMAIL: ${{ secrets.MAINTAIN_EMAIL }}
          MAINTAIN_USERNAME: ${{ secrets.MAINTAIN_USERNAME }}
        run: |
          bash "${GITHUB_WORKSPACE}/.github/scripts/create-git-tag.sh"
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.PACKAGE_VERSION }}
          files: elementor-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.MAINTAIN_TOKEN }}
      - name: Notify Slack
        env:
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_CHANNELS: ${{ secrets.SLACK_CHANNELS }}
        run: |
          bash "${GITHUB_WORKSPACE}/.github/scripts/slack-notify.sh"

