name: Screenshotter

on: [ push, pull_request ]

jobs:
  run:
    runs-on: ubuntu-16.04
    strategy:
      fail-fast: true
      matrix:
        wordpress_versions: [ 'latest' ]
    name: WordPress ${{ matrix.wordpress_versions }}
    steps:
      - name: Startup MySQL service
        run: sudo /etc/init.d/mysql start
      - name: Checkout source code
        uses: actions/checkout@master
        #      - name: Save params as globla in github env
        #        run: |
        #          echo "--db_name=${db_name}" >> $GITHUB_ENV
      - name: Install Screenshotter
        run: |
#          npm i @efelementor/screenshotter --registry=https://npm.pkg.github.com/efelementor
          # Set paths to directories where to install.
          mkdir -p "/tmp/wordpress"
          cd "/tmp/wordpress/"
          echo "$PWD"
          git clone https://github.com/efelementor/elementor-editor-packages/packages/screenshotter.git
          npm i
      - name: Install Dependencies
        run: |
          elementor-vrt-install --wp_version=${{ matrix.wordpress_versions }}
      - name: Import Tamplate(s)
        run: |
          elementor-vrt-import-templates
      - name: Build Package & Run Tests
        run: |
          elementor-vrt-run-test
