name: Slack Version Notify
on:
  workflow_call:

jobs:
  send-slack-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
      - name: Notify Slack
        run: bash "./.github/scripts/slack-notify.sh"
