name: Slack Version Notify
on:
  workflow_call:

jobs:
  send-slack-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Notify Slack
        run: bash "${GITHUB_WORKSPACE}/.github/scripts/slack-notify.sh"
