name: Sync Branches

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  run:
    runs-on: ubuntu-16.04
    if: startsWith( github.repository, 'elementor/' )
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.MAINTAIN_TOKEN }}
          ref: master
      - name: Sync developer-edition branch
        env:
          MAINTAIN_EMAIL: ${{ secrets.MAINTAIN_EMAIL }}
          MAINTAIN_USERNAME: ${{ secrets.MAINTAIN_USERNAME }}
        run: |
          bash "${GITHUB_WORKSPACE}/.github/scripts/sync-developer-edition-branch.sh"
      - name: Sync feature branches into developer-edition branch
        env:
          TOKEN: ${{ secrets.MAINTAIN_TOKEN }}
          REPOSITORY: ${{ github.repository }}
        run: |
          npm install --no-package-lock --no-save @octokit/core@3.3.1
          node "${GITHUB_WORKSPACE}/.github/scripts/sync-features-branch-to-developer-branch.js"
