name: Testim

on:
  pull_request_review:
    types: [submitted]

jobs:
  build-plugin:
    name: Build plugin
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved' && startsWith( github.repository, 'elementor/' )
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Install Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npx grunt build
      - name: Save build to cache
        uses: actions/cache@v2
        id: restore-build
        with:
          path: ./build/*
          key: ${{ github.sha }}

  testim:
    name: testim test - WP ${{ matrix.wpCoreVersion }} on PHP ${{ matrix.phpVersion }}
    runs-on: ubuntu-latest
    needs: [build-plugin]
    strategy:
      matrix:
        include:
          - phpVersion: '7.4'
            wpCoreVersion: 'latest'
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Install Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Restore build from cache
        uses: actions/cache@v2
        id: restore-build
        with:
          path: ./build/*
          key: ${{ github.sha }}
      - name: Update wp-env.json file
        env:
          PHP_VERSION: ${{ matrix.phpVersion }}
          WP_CORE_VERSION: ${{ matrix.wpCoreVersion }}
        run: node ./.github/scripts/build-wp-env.js
      - name: Install wp-env
        run: npm install --no-package-lock --no-save @wordpress/env@4.0.0
      - name: Install WordPress environment
        run: |
          npx wp-env start
          # change wp-env folder owner to www-data
          sudo chown 33:33 -R ~/wp-env/
          npx wp-env run tests-cli "bash -c 'bash elementor-config/import-temapltes.sh'"
      - name: WordPress debug information
        run: |
          npx wp-env run tests-cli "wp core version"
          npx wp-env run tests-cli "wp --info"
      - name: Install Testim
        run: npm install --no-package-lock --no-save @testim/testim-cli
      - name: Install Ngrok
        run: npm install --no-package-lock --no-save ngrok@4.0.1
      - name: Run Testim tests
        run: node ./.github/scripts/testim_ci.js ${{ secrets.TESTIM_PROJECT }} ${{ secrets.TESTIM_TOKEN }} ${{ secrets.NGROK_TOKEN }} 
