name: Test JIRA
on: [push]

jobs:
  test-jira:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate changelog
        env:
          TOKEN: ${{ secrets.MAINTAIN_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          HEAD_BRANCH_NAME: v3.3.0-dev5
          BASE_TAG_NAME: v3.3.0-dev4
        run: |
          npm install --no-package-lock --no-save @octokit/core@3.4.0
          node ./.github/scripts/generate-changelog.js
      - name: Read changelog and set current date
        run: |
          CHANGELOG=$(cat temp-changelog.txt | tr -d '\n')
          NOW=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "CHANGELOG=${CHANGELOG}" >> $GITHUB_ENV
          echo "NOW=${NOW}" >> $GITHUB_ENV
      - name: Parse Jira Keys from changelog
        id: jira_keys
        uses: HighwayThree/jira-extract-issue-keys@8050830121f3eab19553d2f0c0150873a8d1b51b
        with:
          commit-message: '${{ env.CHANGELOG }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Deployment Info to Jira
        if: steps.jira_keys.outputs.jira-keys != ''
        uses: HighwayThree/jira-upload-deployment-info@7cd4db1e5cc96692fd0b4c688407efd95ae3e610
        with:
          client-id: '${{ secrets.JIRA_CLIENT_ID }}'
          client-secret: '${{ secrets.JIRA_CLIENT_SECRET }}'
          cloud-instance-base-url: '${{ secrets.JIRA_CLOUD_INSTANCE_BASE_URL }}'
          issue-keys: "${{ steps.jira_keys.outputs.jira-keys }}"
          display-name: "3.3.0-dev5"
          url: '${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}'
          description: "This PR was merged to the following release(s)"
          last-updated: '${{ env.NOW }}'
          state: 'successful'
          pipeline-url: '${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}'
          environment-id: "3.3.0-dev5"
          environment-display-name: "3.3.0-dev5"
          environment-type: 'staging'
